### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by avinashkarkada** [pablo-arantes/making-it-rain#19]
File "/usr/local/lib/python3.7/dist-packages/biopandas/pdb/pandas_pdb.py", line 369
    if s := header.split():
          ^
SyntaxError: invalid syntax

Gettin this error since yesterday. Any solution?
Thank you

**Comment by pablo-arantes** [comment]
Hi,

I have fixed the notebook. Please, try again and let me know if everything is working fine.

Thank you.

Best,

Pabo

**Comment by avinashkarkada** [comment]
Hey,
Thank you for the quick reply. But unfortunately, the error still exists

**Comment by pablo-arantes** [comment]
Hi,

I have tried here and everything is working fine. Please disconnect, close the notebooks and open again with the links available in the  Making it rain GitHub.

Thank you.

Best,

Pablo

**Comment by Alain-chavanieu** [comment]
Hello

I had the same problem last night. I did try our soluce(disconnect, reload new page etc..)
But i had the problem is still there. I attach the error file
#!pip install biopandas 2>&1 1>/dev/null, before change made by P.A
!pip install git+https://github.com/pablo-arantes/biopandas 2>&1 1>/dev/null

By the way ! Many thanks for these Gc notebook. We now can run a bit more of MD on 450k atom system (sodium channel, we just need about 100ns simulation after docking). 

Alain
 
[UnsatisfiableError.docx](https://github.com/pablo-arantes/making-it-rain/files/8685923/UnsatisfiableError.docx)

**Comment by pablo-arantes** [comment]
Hi @avinashkarkada and @Alain-chavanieu,

I have fixes all the notebooks, please try to run again and let me know if everything is working fine.

Thank you.

Best,

**Comment by Alain-chavanieu** [comment]
Hello

All good. It s working fine. In 8 days, my 100ns run will be ended !
Thank you very much @pablo-arantes.

Alain
